repositories:
  remote:
   - https://repo.maven.apache.org/maven2
artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.3

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  maven_plugin_api: org.apache.maven:maven-plugin-api:jar:3.3.9
  sisu_plexus: org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.2
  plexus_component_annotations: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
  maven_shade_plugin: org.apache.maven.plugins:maven-shade-plugin:jar:2.3
  maven_core: org.apache.maven:maven-core:jar:3.0
  plexus_utils: org.codehaus.plexus:plexus-utils:jar:3.0.15
  asm: org.ow2.asm:asm:jar:5.0.2
  asm_commons: org.ow2.asm:asm-commons:jar:5.0.2
  asm_tree: org.ow2.asm:asm-tree:jar:5.0.2
  guava: com.google.guava:guava:jar:11.0.2

