repositories:
  remote:
   - https://repo.maven.apache.org/maven2
artifacts:
  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.3

  maven_shade_plugin: org.apache.maven.plugins:maven-shade-plugin:jar:3.3.0
  maven_plugin_api: org.apache.maven:maven-plugin-api:jar:3.8.5
  plexus_component_annotations: org.codehaus.plexus:plexus-component-annotations:jar:2.1.1
  plexus_utils: org.codehaus.plexus:plexus-utils:jar:3.4.1
  sisu_plexus: org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5
  maven_core: org.apache.maven:maven-core:jar:3.8.5
  asm: org.ow2.asm:asm:jar:9.3
  asm_commons: org.ow2.asm:asm-commons:jar:9.3
  asm_tree: org.ow2.asm:asm-tree:jar:9.3
  jdependency: org.vafer:jdependency:jar:2.7.0
  commons_collections4: org.apache.commons:commons-collections4:jar:4.4
  slf4j_api: org.slf4j:slf4j-api:jar:1.7.36
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.7.36
  guava: com.google.guava:guava:jar:11.0.2
